/// <reference types="cypress" />

describe('recommendation e2e', () => {
  before(() => {
    cy.resetDatabase()
  })
  it('should create a new recommendation, list it, and upvote it', () => {
    cy.intercept('GET', '/recommendations').as('getRecommendations')
    cy.intercept('POST', '/recommendations').as('postRecommendation')
    cy.visit('http://localhost:3000')
    cy.get('#name').type('final countdown')
    cy.get('#link').type('https://www.youtube.com/watch?v=9jK-NcRmVcw')
    cy.get('#send').click()
    cy.wait('@postRecommendation')
    cy.wait('@getRecommendations')
    cy.get('#arrowUp').click()
    cy.get('#score').should('contain', 1)
    cy.get('article').should(($article) => {
      expect($article).to.have.length(1)
    })
    cy.url().should('equal', 'http://localhost:3000/')
  })

  it('should create a new recommendation, list it and downvote it', () => {
    cy.intercept('GET', '/recommendations').as('getRecommendations')
    cy.intercept('POST', '/recommendations').as('postRecommendation')
    cy.visit('http://localhost:3000')
    cy.get('#name').type('final countdown')
    cy.get('#link').type('https://www.youtube.com/watch?v=9jK-NcRmVcw')
    cy.get('#send').click()
    cy.wait('@postRecommendation')
    cy.wait('@getRecommendations')
    cy.get('#arrowDown').click()
    cy.get('#score').should('contain', -1)
    cy.get('article').should(($article) => {
      expect($article).to.have.length(1)
    })
    cy.url().should('equal', 'http://localhost:3000/')
  })
})

describe('Random page', () => {
  it('should show only one recommendation', () => {
    cy.intercept('GET', '/recommendations/*').as('getRandomRecommendation')
    cy.intercept('POST', '/recommendations').as('postRecommendation')
    cy.visit('http://localhost:3000')
    cy.get('#name').type('final countdown')
    cy.get('#link').type('https://www.youtube.com/watch?v=9jK-NcRmVcw')
    cy.get('#send').click()
    cy.wait('@postRecommendation')
    cy.get('#name').type('final countdown second part')
    cy.get('#link').type('https://www.youtube.com/watch?v=9jK-NcRmVcw')
    cy.get('#send').click()
    cy.wait('@postRecommendation')
    cy.visit('http://localhost:3000/random')
    cy.wait('@getRandomRecommendation')
    cy.get('article').should(($article) => {
      expect($article).to.have.length(1)
    })
    cy.url().should('equal', 'http://localhost:3000/random')
  })
})
describe('Top page', () => {
  it('should show recommendation by score', () => {
    cy.intercept('GET', '/recommendations/*').as('getTopRecommendation')
    cy.intercept('POST', '/recommendations').as('postRecommendation')
    cy.visit('http://localhost:3000')
    cy.get('#name').type('final countdown')
    cy.get('#link').type('https://www.youtube.com/watch?v=9jK-NcRmVcw')
    cy.get('#send').click()
    cy.wait('@postRecommendation')
    cy.get('#name').type('final countdown second part')
    cy.get('#link').type('https://www.youtube.com/watch?v=9jK-NcRmVcw')
    cy.get('#send').click()
    cy.wait('@postRecommendation')
    cy.visit('http://localhost:3000/top')
    cy.wait('@getTopRecommendation')
    cy.get('#final countdown').get('#arrowUp').click()
    cy.wait('@getTopRecommendation')
    cy.get('#name-video').first().should('equal', 'final countdown')
    cy.url().should('equal', 'http://localhost:3000/top')
  })
})
